### ISSUE TITLE
Need support for Visual Studio 2017

### ISSUE THREAD

**Issue by bugged84** [AArnott/CodeGeneration.Roslyn#12]
It seems that the GenerateCodeFromAttributes task does not work in Visual Studio 2017 RC. The error list window shows:

```
Severity	Code	       Description
Warning	        IDE0006	       Error encountered while loading the project. Some project
                               features, such as full solution analysis for the failed
                               project and projects that depend on it, have been disabled.
```

 I was able to find the following error details by enabling design time logs as described in [IDE0006](https://github.com/dotnet/roslyn/wiki/Diagnosing-Project-System-Build-Errors).

```
Build FAILED.

C:\...\packages\CodeGeneration.Roslyn.BuildTime.0.1.57\build\CodeGeneration.Roslyn.BuildTime.targets(20,5):
error MSB4018: The "GenerateCodeFromAttributes" task failed unexpectedly.
System.ArgumentException: Object type cannot be converted to target type.
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Helper.set_Compile(ITaskItem[] value)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by bugged84** [comment]
Here is the source code where the error occurs in the GenerateCodeFromAttributes.cs file:

```
...

namespace CodeGeneration.Roslyn.Tasks
{
  public class GenerateCodeFromAttributes : Microsoft.Build.Utilities.Task, ICancelableTask, ITask
  {
    ...

    [Required]
    public ITaskItem[] Compile { get; set; }
   
    ...

    public override bool Execute()
    {
      AppDomain domain = AppDomain.CreateDomain("codegen", AppDomain.CurrentDomain.Evidence, new AppDomainSetup()
      {
        ApplicationBase = Path.GetDirectoryName(this.GetType().Assembly.Location),
        DisallowBindingRedirects = true
      });

      try
      {
        GenerateCodeFromAttributes.Helper instanceAndUnwrap = (GenerateCodeFromAttributes.Helper) domain.CreateInstanceAndUnwrap(Assembly.GetExecutingAssembly().FullName, typeof (GenerateCodeFromAttributes.Helper).FullName);
        instanceAndUnwrap.Compile = this.Compile;
        ...
        try
        {
          instanceAndUnwrap.Execute();
          ...
        }
        catch (OperationCanceledException ex)
        {
          ...
        }
      }
      finally
      {
        AppDomain.Unload(domain);
      }
    }

    ...
  }
}
```

**Comment by bugged84** [comment]
Seems like source code above could be experiencing this [issue].(https://social.msdn.microsoft.com/Forums/vstudio/en-US/21abf1c6-f8f4-453e-84fa-b540c8b15e72/cannot-run-an-assembly-in-appdomain?forum=csharpgeneral)

**Comment by LokiMidgard** [comment]
I still get this error.

On one maschine my projects are working, now I cheked them out on another maschine and they fail with the descriped error

```
.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018: The "GenerateCodeFromAttributes" task failed unexpectedly.
.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018: System.ArgumentException: Object type cannot be converted to target type.
.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.Tasks.Helper.set_Compile(ITaskItem[] value)
.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```

**Comment by lanfeust69** [comment]
I failed to understand the root cause, but what I saw is that my build (which uses version 0.3.9 of CodeGeneration.Roslyn.BuildTime) fails when there is only VS2017 on the machine. Installing the [Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159) fixed it.

**Comment by amis92** [comment]
Currently the only two imported MSBuild project files are targeting `ToolsVersion=14.0` so I think this can be closed.
