### ISSUE TITLE
Build fails after an update to 0.4.9 

### ISSUE THREAD

**Issue by Pzixel** [AArnott/CodeGeneration.Roslyn#38]
I have a branch for `0.4.9` update: https://github.com/Pzixel/RemoteClient.Roslyn/tree/feature/attributes-usage

Expected: everything is fine, update is successful.
Actual: build fails with an error
![image](https://user-images.githubusercontent.com/11201122/27646374-1cff00b8-5c31-11e7-81f8-634ef0ae72fa.png)

**Comment by AArnott** [comment]
Please include output of package restore.

**Comment by Pzixel** [comment]
I completly removed all repostitory, recloned it an ran build:

```
Restoring NuGet packages...
Running restore with 4 concurrent jobs.
Reading project file C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn\RemoteClient.Roslyn.csproj.
Reading project file C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn.Test\RemoteClient.Roslyn.Test.csproj.
Restoring packages for C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn\RemoteClient.Roslyn.csproj...
Restoring packages for .NETStandard,Version=v1.6...
Restoring packages for C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn.Test\RemoteClient.Roslyn.Test.csproj...
Restoring packages for .NETCoreApp,Version=v1.1...
Resolving conflicts for .NETStandard,Version=v1.6...
Resolving conflicts for .NETCoreApp,Version=v1.1...
Checking compatibility of packages on .NETStandard,Version=v1.6.
All packages and projects are compatible with .NETStandard,Version=v1.6.
Committing restore...
Lock file has not changed. Skipping lock file write. Path: C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn\obj\project.assets.json
Restore completed in 367,05 ms for C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn\RemoteClient.Roslyn.csproj.
Checking compatibility of packages on .NETCoreApp,Version=v1.1.
All packages and projects are compatible with .NETCoreApp,Version=v1.1.
Committing restore...
Lock file has not changed. Skipping lock file write. Path: C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn.Test\obj\project.assets.json
Restore completed in 728,37 ms for C:\Users\SOLO\Documents\Repos\github\RemoteClient.Roslyn\RemoteClient.Roslyn.Test\RemoteClient.Roslyn.Test.csproj.
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.7551665
========== Finished ==========


```

```
2>Target GenerateCodeFromAttributes:
2>  Using "GenerateCodeFromAttributes" task from assembly "C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\net46\CodeGeneration.Roslyn.Tasks.dll".
2>  Task "GenerateCodeFromAttributes"
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018: The "GenerateCodeFromAttributes" task failed unexpectedly.
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018: System.InvalidOperationException: Unable to find code generator: RemoteClient.Roslyn.RemoteClientGenerator, RemoteClient.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at Validation.Verify.Operation(Boolean condition, String unformattedMessage, Object arg1)
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.DocumentTransform.<FindCodeGenerators>d__3.MoveNext()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.DocumentTransform.<TransformAsync>d__2.MoveNext()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.Tasks.Helper.<<Execute>b__36_1>d.MoveNext()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.Tasks.Helper.Execute()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.Tasks.Helper.Execute()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>    C:\Users\SOLO\.nuget\packages\codegeneration.roslyn.buildtime\0.3.9\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>  Done executing task "GenerateCodeFromAttributes" -- FAILED.
```
You can see `0.3.9` here, however full text search shows that I haven't any line with `0.3.9` in my repository.

**Comment by Pzixel** [comment]
Ok, I found the issue: it's my environment which was blocking this request. Sorry for disturbing.
